# Site settings
title: '#tirandoparo'
description: "Guía contra la desinformación. Contenidos con lineamientos para evitar la desinformación en los entornos digitales. Una iniciativa por diseñadores y comunicólogos de Centro y la Ibero."
url: "http://tirandoparo.mx"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 6
paginate_path: /pagina_:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-last-modified-at

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true
